services:
  database:
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    environment:
      POSTGRES_USER: weblog
      POSTGRES_PASSWORD: weblogpass
      POSTGRES_DB: weblogdb
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
      target: development
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./internal:/app/internal
      - ./cmd:/app/cmd
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
      target: development
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
